'use strict';

const assert = require('node:assert/strict');
const { Readable } = require('node:stream');
const test = require('node:test');

const {
  SYSTEM_FETCH_BRIDGE_MARKER,
  byteStringSafeResponseHeaderValue,
  chromiumResponseHeaders,
  createSystemFetchBridge,
  installChromiumResponseHeaderBridge,
  installGlobalSystemFetchBridge,
} = require('../electron/systemFetchBridge.cjs');

function createFetchRecorder(label) {
  const calls = [];
  const fetchImpl = async (input, init) => {
    calls.push({ input, init });
    return { label, input, init };
  };
  return { calls, fetchImpl };
}

test('ordinary HTTP(S) requests use Chromium fetch', async () => {
  const chromium = createFetchRecorder('chromium');
  const node = createFetchRecorder('node');
  const bridge = createSystemFetchBridge({
    chromiumFetch: chromium.fetchImpl,
    nodeFetch: node.fetchImpl,
  });

  const httpResult = await bridge('http://example.test/image');
  const httpsResult = await bridge(new URL('https://example.test/video'), {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: '{"prompt":"hello"}',
  });

  assert.equal(httpResult.label, 'chromium');
  assert.equal(httpsResult.label, 'chromium');
  assert.equal(chromium.calls.length, 2);
  assert.equal(node.calls.length, 0);
  assert.equal(chromium.calls[1].input.href, 'https://example.test/video');
  assert.equal(chromium.calls[1].init.method, 'POST');
});

test('Chromium transport strips caller-supplied authority and body-framing headers', async () => {
  const forbiddenHeaders = {
    Host: 'https://wrong-authority.example',
    Connection: 'close',
    'Proxy-Connection': 'keep-alive',
    'Keep-Alive': 'timeout=5',
    'Content-Length': '2',
    'Transfer-Encoding': 'chunked',
    TE: 'trailers',
    Trailer: 'x-checksum',
    Upgrade: 'websocket',
    Expect: '100-continue',
  };
  const variants = [
    { ...forbiddenHeaders, Authorization: 'Bearer safe', 'Content-Type': 'application/json' },
    Object.entries({ ...forbiddenHeaders, Authorization: 'Bearer safe', 'Content-Type': 'application/json' }),
    new Headers({ ...forbiddenHeaders, Authorization: 'Bearer safe', 'Content-Type': 'application/json' }),
  ];

  for (const headers of variants) {
    const chromium = createFetchRecorder('chromium');
    const node = createFetchRecorder('node');
    const bridge = createSystemFetchBridge({
      chromiumFetch: chromium.fetchImpl,
      nodeFetch: node.fetchImpl,
    });

    await bridge('https://www.runninghub.cn/task/openapi/outputs', {
      method: 'POST',
      headers,
      body: '{}',
    });

    const forwarded = new Headers(chromium.calls[0].init.headers);
    for (const name of Object.keys(forbiddenHeaders)) {
      assert.equal(forwarded.has(name), false, `${name} must be generated by Chromium`);
    }
    assert.equal(forwarded.get('authorization'), 'Bearer safe');
    assert.equal(forwarded.get('content-type'), 'application/json');
    assert.equal(node.calls.length, 0);
  }

  const chromium = createFetchRecorder('chromium-request');
  const node = createFetchRecorder('node-request');
  const bridge = createSystemFetchBridge({
    chromiumFetch: chromium.fetchImpl,
    nodeFetch: node.fetchImpl,
  });
  const request = new Request('https://www.runninghub.cn/api/webapp/apiCallDemo', {
    headers: {
      Host: 'https://wrong-authority.example',
      'Content-Length': '2',
      Authorization: 'Bearer safe',
    },
  });
  await bridge(request);
  const requestHeaders = new Headers(chromium.calls[0].init.headers);
  assert.equal(requestHeaders.has('host'), false);
  assert.equal(requestHeaders.has('content-length'), false);
  assert.equal(requestHeaders.get('authorization'), 'Bearer safe');
  assert.equal(node.calls.length, 0);

  assert.equal(forbiddenHeaders.Host, 'https://wrong-authority.example', 'caller headers remain untouched');
});

test('Chromium response headers preserve UTF-8 paths as ByteString-safe bytes', () => {
  const unicodePath = 'C:\\Users\\自定义用户\\AppData\\Roaming\\T8-PenguinCanvas\\输出图.png';
  const expected = Buffer.from(unicodePath, 'utf8').toString('latin1');
  const normalized = chromiumResponseHeaders({
    'Content-Disposition': [`attachment; filename="${unicodePath}"`],
    'X-Output-Path': [unicodePath],
    'Content-Type': ['image/png'],
  });

  assert.equal(
    normalized['Content-Disposition'][0],
    `attachment; filename="${Buffer.from(unicodePath, 'utf8').toString('latin1')}"`,
  );
  assert.equal(normalized['X-Output-Path'][0], expected);
  assert.equal(normalized['Content-Type'][0], 'image/png');
  assert.equal(Buffer.from(normalized['X-Output-Path'][0], 'latin1').toString('utf8'), unicodePath);
  assert.doesNotThrow(() => new Headers(normalized));
});

test('ASCII and latin1 response headers retain their original identity', () => {
  const headers = {
    'Content-Type': ['application/json'],
    ETag: ['"caf\u00e9"'],
  };
  assert.strictEqual(chromiumResponseHeaders(headers), headers);
  assert.equal(byteStringSafeResponseHeaderValue('caf\u00e9'), 'caf\u00e9');
});

test('response header bridge is idempotent and changes only Unicode values', () => {
  const registrations = [];
  const networkSession = {
    webRequest: {
      onHeadersReceived(filter, listener) {
        registrations.push({ filter, listener });
      },
    },
  };

  installChromiumResponseHeaderBridge(networkSession);
  installChromiumResponseHeaderBridge(networkSession);
  assert.equal(registrations.length, 1);
  assert.deepEqual(registrations[0].filter, { urls: ['http://*/*', 'https://*/*'] });

  const unicodeValue = 'C:\\Users\\自媒体\\图片.png';
  let unicodeResult;
  registrations[0].listener({ responseHeaders: { 'X-Path': [unicodeValue] } }, (result) => {
    unicodeResult = result;
  });
  assert.equal(
    unicodeResult.responseHeaders['X-Path'][0],
    Buffer.from(unicodeValue, 'utf8').toString('latin1'),
  );

  let asciiResult;
  registrations[0].listener({ responseHeaders: { 'Content-Type': ['image/png'] } }, (result) => {
    asciiResult = result;
  });
  assert.deepEqual(asciiResult, {});

  let rendererResult;
  registrations[0].listener({
    webContentsId: 7,
    responseHeaders: { 'X-Path': [unicodeValue] },
  }, (result) => {
    rendererResult = result;
  });
  assert.deepEqual(rendererResult, {});
});

test('healthy requests do not reload proxy or DNS state', async () => {
  const chromium = createFetchRecorder('chromium');
  const node = createFetchRecorder('node');
  let refreshCalls = 0;
  const bridge = createSystemFetchBridge({
    chromiumFetch: chromium.fetchImpl,
    nodeFetch: node.fetchImpl,
    refreshNetwork: async () => { refreshCalls += 1; },
  });

  await bridge('https://example.test/status');

  assert.equal(chromium.calls.length, 1);
  assert.equal(refreshCalls, 0);
});

test('failed GET refreshes system networking and retries once through Chromium', async () => {
  const node = createFetchRecorder('node');
  let chromiumCalls = 0;
  let refreshCalls = 0;
  const bridge = createSystemFetchBridge({
    chromiumFetch: async () => {
      chromiumCalls += 1;
      if (chromiumCalls === 1) throw new TypeError('fetch failed');
      return { label: 'chromium-recovered' };
    },
    nodeFetch: node.fetchImpl,
    refreshNetwork: async () => { refreshCalls += 1; },
    refreshIntervalMs: 0,
  });

  const result = await bridge('https://example.test/status');

  assert.equal(result.label, 'chromium-recovered');
  assert.equal(chromiumCalls, 2);
  assert.equal(refreshCalls, 1);
  assert.equal(node.calls.length, 0);
});

test('failed POST refreshes the next connection but never replays the write', async () => {
  const node = createFetchRecorder('node');
  let chromiumCalls = 0;
  let refreshCalls = 0;
  const bridge = createSystemFetchBridge({
    chromiumFetch: async () => {
      chromiumCalls += 1;
      throw new TypeError('fetch failed');
    },
    nodeFetch: node.fetchImpl,
    refreshNetwork: async () => { refreshCalls += 1; },
    refreshIntervalMs: 0,
  });

  await assert.rejects(
    bridge('https://example.test/generate', { method: 'POST', body: '{"prompt":"safe"}' }),
    /fetch failed/,
  );

  assert.equal(chromiumCalls, 1);
  assert.equal(refreshCalls, 1);
  assert.equal(node.calls.length, 0);
});

test('explicit dispatcher or agent keeps the request on Node fetch', async () => {
  const chromium = createFetchRecorder('chromium');
  const node = createFetchRecorder('node');
  const bridge = createSystemFetchBridge({
    chromiumFetch: chromium.fetchImpl,
    nodeFetch: node.fetchImpl,
  });
  const dispatcher = { name: 'undici-dispatcher' };
  const agent = { name: 'node-agent' };

  const dispatcherResult = await bridge('https://example.test/poll', { dispatcher });
  const agentResult = await bridge('https://example.test/download', { agent });

  assert.equal(dispatcherResult.label, 'node');
  assert.equal(agentResult.label, 'node');
  assert.equal(chromium.calls.length, 0);
  assert.equal(node.calls.length, 2);
  assert.strictEqual(node.calls[0].init.dispatcher, dispatcher);
  assert.strictEqual(node.calls[1].init.agent, agent);
});

test('Node stream request bodies keep the request on Node fetch', async () => {
  const chromium = createFetchRecorder('chromium');
  const node = createFetchRecorder('node');
  const bridge = createSystemFetchBridge({
    chromiumFetch: chromium.fetchImpl,
    nodeFetch: node.fetchImpl,
  });
  const body = Readable.from(['provider-upload']);

  const result = await bridge('https://example.test/upload', {
    method: 'POST',
    headers: { 'Content-Length': '15' },
    body,
    duplex: 'half',
  });

  assert.equal(result.label, 'node');
  assert.equal(chromium.calls.length, 0);
  assert.equal(node.calls.length, 1);
  assert.strictEqual(node.calls[0].init.body, body);
  assert.equal(node.calls[0].init.duplex, 'half');
  assert.equal(node.calls[0].init.headers['Content-Length'], '15');
});

test('Request objects carrying stream bodies remain on Node fetch', async () => {
  const chromium = createFetchRecorder('chromium');
  const node = createFetchRecorder('node');
  const bridge = createSystemFetchBridge({
    chromiumFetch: chromium.fetchImpl,
    nodeFetch: node.fetchImpl,
  });
  const request = new Request('https://example.test/upload', {
    method: 'POST',
    body: Readable.toWeb(Readable.from(['provider-upload'])),
    duplex: 'half',
  });

  const result = await bridge(request);

  assert.equal(result.label, 'node');
  assert.equal(chromium.calls.length, 0);
  assert.equal(node.calls.length, 1);
  assert.strictEqual(node.calls[0].input, request);
});

test('non-HTTP protocols keep the request on Node fetch', async () => {
  const chromium = createFetchRecorder('chromium');
  const node = createFetchRecorder('node');
  const bridge = createSystemFetchBridge({
    chromiumFetch: chromium.fetchImpl,
    nodeFetch: node.fetchImpl,
  });

  const fileResult = await bridge('file:///C:/temporary/provider-result.json');
  const dataResult = await bridge('data:text/plain,canvas');

  assert.equal(fileResult.label, 'node');
  assert.equal(dataResult.label, 'node');
  assert.equal(chromium.calls.length, 0);
  assert.equal(node.calls.length, 2);
});

test('global installation is idempotent and keeps the original Node fallback', async () => {
  const chromium = createFetchRecorder('chromium');
  const node = createFetchRecorder('node');
  const target = { fetch: node.fetchImpl };

  const first = installGlobalSystemFetchBridge({
    target,
    chromiumFetch: chromium.fetchImpl,
  });
  const second = installGlobalSystemFetchBridge({
    target,
    chromiumFetch: async () => {
      throw new Error('idempotent install must not replace the existing bridge');
    },
  });

  assert.strictEqual(first, second);
  assert.strictEqual(target.fetch, first);
  assert.ok(first[SYSTEM_FETCH_BRIDGE_MARKER]);

  const httpResult = await target.fetch('https://example.test/provider');
  const nodeResult = await target.fetch('file:///C:/temporary/provider-result.json');

  assert.equal(httpResult.label, 'chromium');
  assert.equal(nodeResult.label, 'node');
  assert.equal(chromium.calls.length, 1);
  assert.equal(node.calls.length, 1);
});

test('bridge marker preserves the Chromium resolver used for trusted output validation', () => {
  const chromium = createFetchRecorder('chromium');
  const node = createFetchRecorder('node');
  const resolveHost = async () => ({
    endpoints: [{ address: '203.0.113.10', family: 'ipv4' }],
  });
  const bridge = createSystemFetchBridge({
    chromiumFetch: chromium.fetchImpl,
    nodeFetch: node.fetchImpl,
    resolveHost,
  });

  assert.strictEqual(bridge[SYSTEM_FETCH_BRIDGE_MARKER].resolveHost, resolveHost);
});
