'use strict';

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const SOURCE = path.join(ROOT, 'tools', 'zcanvas-cli', 'creativeCapabilityManifest.json');
const ZCANVAS_MANIFEST = path.join(ROOT, 'tools', 'zcanvas-cli', 'manifest.json');
const COMMAND_CATALOG_SOURCE = path.join(ROOT, 'tools', 'zcanvas-cli', 'commandCatalogSource.json');
const COMMAND_CATALOG_TARGET = path.join(ROOT, 'tools', 'zcanvas-cli', 'commandCatalog.json');
const JSON_TARGET = path.join(ROOT, 'tools', 'zcanvas-cli', 'generated', 'creative-capabilities.json');
const MARKDOWN_TARGET = path.join(
  ROOT,
  '.agents',
  'skills',
  'zhenzhen-canvas',
  'references',
  'generated-capabilities.md',
);
const SURFACES_BACKEND_TARGET = path.join(ROOT, 'backend', 'src', 'shared', 'creativeCapabilitySurfaces.json');
const SURFACES_CLI_TARGET = path.join(ROOT, 'tools', 'zcanvas-cli', 'generated', 'creative-capability-surfaces.json');
const SURFACES_UI_TARGET = path.join(ROOT, 'src', 'generated', 'creator-agent-capability-surfaces.json');
const SURFACES_SKILL_TARGET = path.join(
  ROOT,
  '.agents',
  'skills',
  'zhenzhen-canvas',
  'references',
  'generated-capability-surfaces.json',
);

const {
  validateCreativeCapabilityManifest,
} = require(path.join(ROOT, 'backend', 'src', 'services', 'agentControlCapabilities.js'));
const {
  BACKEND_TARGET: RUNTIME_BACKEND_TARGET,
  CLI_TARGET: RUNTIME_CLI_TARGET,
  buildRuntimeCatalog,
  runtimeCatalogArtifact,
} = require('./generateCreativeRuntimeCatalog.cjs');
const {
  BACKEND_TARGET: GRAPH_BACKEND_TARGET,
  CLI_TARGET: GRAPH_CLI_TARGET,
  MARKDOWN_TARGET: GRAPH_MARKDOWN_TARGET,
  buildCapabilityGraph,
  coverageMarkdownArtifact,
  graphArtifact,
} = require('./creativeCapabilityGraphArtifacts.cjs');

function readManifest() {
  const raw = fs.readFileSync(SOURCE);
  const manifest = validateCreativeCapabilityManifest(JSON.parse(raw.toString('utf8')));
  if (manifest.capabilities.length === 0) throw new Error('creative capability manifest is empty');
  return {
    raw,
    manifest,
    digest: crypto.createHash('sha256').update(raw).digest('hex'),
  };
}

function validateCompatibilityManifest(capabilityGraph) {
  const manifest = JSON.parse(fs.readFileSync(ZCANVAS_MANIFEST, 'utf8'));
  if (manifest?.schema !== 't8-zcanvas-manifest-v1'
    || manifest.creativeCapabilityManifest !== 'creativeCapabilityManifest.json'
    || manifest.creativeCapabilityGraph !== 'generated/creative-capability-graph.json'
    || manifest.creativeCapabilitySurfaces !== 'generated/creative-capability-surfaces.json') {
    throw new Error('zcanvas compatibility manifest does not declare the generated capability graph');
  }
  if (String(manifest.nodeSchemaDigest || '') !== capabilityGraph.sourceDigests.canvasNodeSchema) {
    throw new Error(
      `zcanvas nodeSchemaDigest drift: expected ${capabilityGraph.sourceDigests.canvasNodeSchema}`,
    );
  }
  if (String(manifest.providerCatalogDigest || '') !== capabilityGraph.sourceDigests.runtimeCatalogArtifact) {
    throw new Error(
      `zcanvas providerCatalogDigest drift: expected ${capabilityGraph.sourceDigests.runtimeCatalogArtifact}`,
    );
  }
  return manifest;
}
function jsonArtifact(manifest, digest, capabilityGraph = null) {
  const graphNodeTypes = new Map(
    (capabilityGraph?.capabilities || []).map((capability) => [capability.id, capability.nodeTypes]),
  );
  return `${JSON.stringify({
    schema: 't8-generated-creative-capability-index-v1',
    generatedFrom: 'tools/zcanvas-cli/creativeCapabilityManifest.json',
    sourceSchema: manifest.schema,
    sourceVersion: manifest.version,
    sourceDigest: digest,
    principles: manifest.principles,
    capabilities: manifest.capabilities.map((capability) => ({
      id: capability.id,
      creatorLabel: capability.creatorLabel,
      summary: capability.summary,
      category: capability.category,
      approval: capability.approval,
      handler: capability.handler,
      nodeTypes: graphNodeTypes.get(capability.id) || capability.nodeTypes,
      supports: capability.supports,
      inputKinds: capability.inputKinds,
      outputKinds: capability.outputKinds,
    })),
  }, null, 2)}\n`;
}

function markdownArtifact(manifest, digest) {
  const grouped = new Map();
  for (const capability of manifest.capabilities) {
    const category = String(capability.category || 'other');
    if (!grouped.has(category)) grouped.set(category, []);
    grouped.get(category).push(capability);
  }
  const lines = [
    '# Generated creative capabilities',
    '',
    '> Machine-generated from `tools/zcanvas-cli/creativeCapabilityManifest.json`.',
    '> Do not edit this file by hand. It is an index only and never overrides the Skill safety contract.',
    '',
    `- Source schema: \`${manifest.schema}\``,
    `- Source version: \`${manifest.version}\``,
    `- Source SHA-256: \`${digest}\``,
    `- Registered capabilities: **${manifest.capabilities.length}**`,
    '',
    'All write or generation paths shown here remain subject to the human-readable Skill rules:',
    'inspect → plan → preview → explicit approval → apply/run → verify.',
    '',
  ];
  for (const [category, capabilities] of grouped.entries()) {
    lines.push(`## ${category}`, '');
    for (const capability of capabilities) {
      lines.push(
        `- \`${capability.id}\` — **${capability.creatorLabel}** (${capability.approval}): ${capability.summary}`,
        `  - handler: \`${capability.handler}\``,
        `  - supports: ${(capability.supports || []).map((item) => `\`${item}\``).join(', ') || 'none'}`,
      );
    }
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

function buildCommandCatalog(manifest) {
  const sourceCatalog = JSON.parse(fs.readFileSync(COMMAND_CATALOG_SOURCE, 'utf8'));
  if (sourceCatalog?.schema !== 't8-zcanvas-command-catalog-source-v1'
    || !Array.isArray(sourceCatalog.commands)) {
    throw new Error('zcanvas command catalog source schema is invalid');
  }
  const commands = sourceCatalog.commands.map((command) => ({
    name: String(command?.name || '').trim(),
    summary: String(command?.summary || '').trim(),
    available: command?.available === true,
    subcommands: Array.isArray(command?.subcommands)
      ? command.subcommands.map((subcommand) => String(subcommand || '').trim())
      : [],
  }));
  const commandByName = new Map();
  const cliOperations = new Set();
  for (const command of commands) {
    if (!/^[a-z][a-z0-9-]*$/.test(command.name)
      || !command.summary
      || commandByName.has(command.name)
      || command.subcommands.some((subcommand) => !/^[a-z][a-z0-9-]*$/.test(subcommand))) {
      throw new Error(`zcanvas command catalog source has an invalid command: ${command.name || '(empty)'}`);
    }
    commandByName.set(command.name, command);
    for (const subcommand of command.subcommands) {
      const operation = `${command.name}.${subcommand}`;
      if (cliOperations.has(operation)) {
        throw new Error(`zcanvas command catalog source duplicates operation: ${operation}`);
      }
      cliOperations.add(operation);
    }
  }
  for (const capability of manifest.capabilities) {
    const commandName = String(capability?.cli?.command || '').trim();
    const subcommand = String(capability?.cli?.subcommand || '').trim();
    const operation = `${commandName}.${subcommand}`;
    const command = commandByName.get(commandName);
    if (!command) throw new Error(`Creative capability ${capability.id} references missing CLI command ${commandName}`);
    if (cliOperations.has(operation)) {
      throw new Error(`Creative capability ${capability.id} duplicates CLI operation ${operation}`);
    }
    command.subcommands.push(subcommand);
    cliOperations.add(operation);
  }
  return {
    schema: 't8-zcanvas-command-catalog-v1',
    commands,
  };
}

function commandCatalogArtifact(catalog) {
  return `${JSON.stringify(catalog, null, 2)}\n`;
}

function requestActionForCapability(capability) {
  const handler = String(capability?.handler || '').trim();
  const separator = handler.indexOf(':');
  if (separator <= 0 || separator === handler.length - 1) {
    throw new Error(`Creative capability ${capability?.id || '(empty)'} has an invalid handler surface`);
  }
  const family = handler.slice(0, separator);
  const operation = handler.slice(separator + 1);
  return family.startsWith('creative-') ? operation : `${family}.${operation}`;
}

const VERSIONED_TOOL_PROTOCOL = 't8-versioned-creative-tool-v1';
const VERSIONED_TOOL_REQUEST_SCHEMA = 't8-versioned-creative-tool-request-v1';
const VERSIONED_TOOL_RESULT_SCHEMA = 't8-versioned-creative-tool-result-v1';
const DIRECT_TOOL_METHOD_OPERATIONS = Object.freeze({
  createPlan: Object.freeze(['plan', 'preview']),
  actionPlan: Object.freeze(['plan', 'preview']),
  readAction: Object.freeze(['inspect', 'compare', 'verify']),
  startPreview: Object.freeze(['preview']),
  inspectPlace: Object.freeze(['preview']),
  inspectImport: Object.freeze(['preview']),
  inspectPackage: Object.freeze(['preview']),
  createBrowserHandoff: Object.freeze(['preview']),
});
const DEFAULT_TOOL_OPERATION_PRIORITY = Object.freeze([
  'plan',
  'inspect',
  'compare',
  'preview',
  'verify',
]);

function directToolOperations(binding, graphCapability) {
  const supported = new Set(graphCapability.operations
    .filter((operation) => operation.riskLevel === 'L0' && operation.approvalRequired === false)
    .map((operation) => operation.operation));
  const direct = (DIRECT_TOOL_METHOD_OPERATIONS[binding.method] || [])
    .filter((operation) => supported.has(operation));
  if (direct.length < 1) {
    throw new Error(`Creative capability ${graphCapability.id} has no safe direct Agent tool operation`);
  }
  return direct;
}

function buildCapabilitySurfaces(manifest, manifestDigest, capabilityGraph) {
  const graphById = new Map(capabilityGraph.capabilities.map((capability) => [capability.id, capability]));
  const bindingById = new Map(capabilityGraph.bindings.map((binding) => [binding.capabilityId, binding]));
  const capabilities = manifest.capabilities.map((capability) => {
    const graphCapability = graphById.get(capability.id);
    const binding = bindingById.get(capability.id);
    if (!graphCapability || !binding) {
      throw new Error(`Creative capability ${capability.id} is missing graph or Agent tool binding`);
    }
    const cliOperation = `${capability.cli.command}.${capability.cli.subcommand}`;
    const requestAction = requestActionForCapability(capability);
    const directOperations = directToolOperations(binding, graphCapability);
    const defaultOperation = DEFAULT_TOOL_OPERATION_PRIORITY
      .find((operation) => directOperations.includes(operation)) || directOperations[0];
    return {
      id: capability.id,
      creatorLabel: capability.creatorLabel,
      category: capability.category,
      approval: capability.approval,
      requiredScopes: [...capability.requiredScopes],
      supports: [...capability.supports],
      agentTool: {
        name: `zcanvas_${capability.id.replace(/[.-]+/g, '_')}`,
        version: manifest.version,
        protocol: VERSIONED_TOOL_PROTOCOL,
        requestSchema: VERSIONED_TOOL_REQUEST_SCHEMA,
        resultSchema: VERSIONED_TOOL_RESULT_SCHEMA,
        defaultOperation,
        directOperations,
        requestAction,
        handler: capability.handler,
        service: binding.service,
        method: binding.method,
        bindingOperation: binding.operation,
      },
      cli: {
        command: capability.cli.command,
        subcommand: capability.cli.subcommand,
        operation: cliOperation,
      },
      ui: {
        action: capability.id,
        requestAction,
        operations: graphCapability.operations.map((operation) => ({ ...operation })),
      },
    };
  });
  return {
    schema: 't8-creative-capability-surfaces-v1',
    capabilityManifestVersion: manifest.version,
    generatedFrom: {
      capabilityManifest: 'tools/zcanvas-cli/creativeCapabilityManifest.json',
      capabilityGraph: 'tools/zcanvas-cli/generated/creative-capability-graph.json',
    },
    sourceDigest: manifestDigest,
    capabilityGraphDigest: capabilityGraph.aggregateDigest,
    counts: {
      capabilities: capabilities.length,
      agentTools: capabilities.length,
      cliOperations: capabilities.length,
      uiActions: capabilities.length,
    },
    capabilities,
  };
}

function capabilitySurfacesArtifact(surfaces) {
  return `${JSON.stringify(surfaces, null, 2)}\n`;
}

function sameFile(filename, expected) {
  try {
    return fs.readFileSync(filename, 'utf8') === expected;
  } catch (error) {
    if (error?.code === 'ENOENT') return false;
    throw error;
  }
}

function writeAtomic(filename, content) {
  fs.mkdirSync(path.dirname(filename), { recursive: true });
  const temporary = `${filename}.${process.pid}.tmp`;
  fs.writeFileSync(temporary, content, { encoding: 'utf8', flag: 'w' });
  fs.renameSync(temporary, filename);
}

function main(argv = process.argv.slice(2)) {
  const check = argv.includes('--check');
  const { manifest, digest } = readManifest();
  const runtimeCatalog = buildRuntimeCatalog();
  const commandCatalog = buildCommandCatalog(manifest);
  const runtimeCatalogContent = runtimeCatalogArtifact(runtimeCatalog);
  const capabilityGraph = buildCapabilityGraph({
    manifest,
    manifestDigest: digest,
    runtimeCatalog,
  });
  const capabilityGraphContent = graphArtifact(capabilityGraph);
  const capabilitySurfaces = buildCapabilitySurfaces(manifest, digest, capabilityGraph);
  const capabilitySurfacesContent = capabilitySurfacesArtifact(capabilitySurfaces);
  validateCompatibilityManifest(capabilityGraph);
  const outputs = [
    [COMMAND_CATALOG_TARGET, commandCatalogArtifact(commandCatalog)],
    [JSON_TARGET, jsonArtifact(manifest, digest, capabilityGraph)],
    [MARKDOWN_TARGET, markdownArtifact(manifest, digest)],
    [SURFACES_BACKEND_TARGET, capabilitySurfacesContent],
    [SURFACES_CLI_TARGET, capabilitySurfacesContent],
    [SURFACES_UI_TARGET, capabilitySurfacesContent],
    [SURFACES_SKILL_TARGET, capabilitySurfacesContent],
    [RUNTIME_BACKEND_TARGET, runtimeCatalogContent],
    [RUNTIME_CLI_TARGET, runtimeCatalogContent],
    [GRAPH_BACKEND_TARGET, capabilityGraphContent],
    [GRAPH_CLI_TARGET, capabilityGraphContent],
    [GRAPH_MARKDOWN_TARGET, coverageMarkdownArtifact(capabilityGraph)],
  ];
  const drift = outputs.filter(([filename, content]) => !sameFile(filename, content));
  if (check) {
    if (drift.length) {
      for (const [filename] of drift) {
        process.stderr.write(`creative capability artifact drift: ${path.relative(ROOT, filename)}\n`);
      }
      process.exitCode = 1;
      return;
    }
    process.stdout.write(
      `creative capability artifacts are current (${manifest.capabilities.length} actions, `
      + `${Object.values(runtimeCatalog.counts).reduce((sum, value) => sum + value, 0)} runtime entries, `
      + `${capabilityGraph.counts.accountedNodes}/${capabilityGraph.counts.nodes} nodes accounted `
      + `(${capabilityGraph.counts.directCapabilityNodes} direct + `
      + `${capabilityGraph.counts.internalCompatNodes} internal + `
      + `${capabilityGraph.counts.semanticSupersededNodes} superseded + `
      + `${capabilityGraph.counts.publicCapabilityGapNodes} public gaps), `
      + `${capabilityGraph.aggregateDigest})\n`,
    );
    return;
  }
  for (const [filename, content] of drift) writeAtomic(filename, content);
  process.stdout.write(
    `generated ${outputs.length} creative capability artifacts (${manifest.capabilities.length} actions, `
    + `${Object.values(runtimeCatalog.counts).reduce((sum, value) => sum + value, 0)} runtime entries, `
    + `${capabilityGraph.counts.accountedNodes}/${capabilityGraph.counts.nodes} nodes accounted `
    + `(${capabilityGraph.counts.directCapabilityNodes} direct + `
    + `${capabilityGraph.counts.internalCompatNodes} internal + `
    + `${capabilityGraph.counts.semanticSupersededNodes} superseded + `
    + `${capabilityGraph.counts.publicCapabilityGapNodes} public gaps), `
    + `${capabilityGraph.aggregateDigest})\n`,
  );
}

if (require.main === module) main();

module.exports = {
  COMMAND_CATALOG_SOURCE,
  COMMAND_CATALOG_TARGET,
  JSON_TARGET,
  MARKDOWN_TARGET,
  SURFACES_BACKEND_TARGET,
  SURFACES_CLI_TARGET,
  SURFACES_UI_TARGET,
  SURFACES_SKILL_TARGET,
  buildCommandCatalog,
  buildCapabilitySurfaces,
  capabilitySurfacesArtifact,
  commandCatalogArtifact,
  RUNTIME_BACKEND_TARGET,
  RUNTIME_CLI_TARGET,
  GRAPH_BACKEND_TARGET,
  GRAPH_CLI_TARGET,
  GRAPH_MARKDOWN_TARGET,
  jsonArtifact,
  main,
  markdownArtifact,
  buildCapabilityGraph,
  coverageMarkdownArtifact,
  graphArtifact,
  readManifest,
  validateCompatibilityManifest,
  runtimeCatalogArtifact,
};
